version: 2.1

jobs:
  hello:
    docker:
      - image: cimg/node:15.2
    steps:
      - checkout
      - run: echo "Hellloooo!"
  build:
    docker:
      - image: cimg/node:15.2
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  hello-build:
    jobs:
      - hello
      - build
