version: 2.1

jobs:
  hello:
    docker:
      - image: cimg/node:15.2
    steps:
      - checkout
      - run: echo "Hellloooo!"
  test:
    docker:
      - image: cimg/node:15.2
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  hello-test:
    jobs:
      - hello
      - test
