version: 2.1

jobs:
  hello:
    docker:
      - image: cimg/node:15.2
    steps:
      - checkout
      - run: echo "Hellloooo!"
  build:
    docker:
      - image: cimg/node:15.2
    steps:
      - checkout
      - run: npm install
      - run: CI=true npm start
workflows:
  hello-build:
    jobs:
      - hello
      - build